#!/usr/bin/env python3
"""Run the five required demonstration scenarios and save the transcripts.

Requirement 4.6 asks for at least five dialogues covering: an answer from the
report corpus, an answer from web search, a combined answer, a call to the
forecasting module, and correct handling of an out-of-scope request.

The transcripts are generated by actually running the agent, not written by
hand. That is the point: a hand-written transcript demonstrates what we hoped
would happen, and this file has to demonstrate what does.

Usage:
    python scripts/run_demo.py [--out demo] [--only 3]
"""

from __future__ import annotations

import argparse
import sys
import time
import traceback
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from neftegaz.agent.graph import answer_question  # noqa: E402
from neftegaz.config import settings  # noqa: E402

SCENARIOS = [
    {
        "id": 1,
        "title": "Ответ на основе отчёта",
        "question": "Что EIA прогнозирует по добыче нефти в США и по мировым запасам?",
        "expect": "Ответ опирается на базу отчётов, ссылки вида [Отчёт …, с. N].",
    },
    {
        "id": 2,
        "title": "Ответ на основе веб-поиска",
        "question": "Какие сейчас котировки Brent и что говорят о них последние новости?",
        "expect": (
            "Вопрос про «сейчас» — отчёты периодические и на него не отвечают, "
            "поэтому агент обязан уйти в веб. Ссылки вида [Источник: …, web]."
        ),
    },
    {
        "id": 3,
        "title": "Комбинированный ответ",
        "question": (
            "Как текущая политика ОПЕК+ по добыче соотносится с последними "
            "прогнозами баланса спроса и предложения?"
        ),
        "expect": "Структурная часть — из отчётов, актуальная — из веба, ссылки раздельные.",
    },
    {
        "id": 4,
        "title": "Вызов расчётного модуля",
        "question": "Спрогнозируй цену Brent на 3 месяца и оцени диапазон при сокращении добычи на 1.5 млн барр./сут",
        "expect": "Агент сам вызывает расчётный модуль, возвращает прогноз с доверительным интервалом.",
    },
    {
        "id": 5,
        "title": "Запрос вне компетенции",
        "question": "Посоветуй, пожалуйста, хороший рецепт борща",
        "expect": "Агент отказывается, объясняет свою область и предлагает переформулировать.",
    },
]


def render(scenario: dict, state: dict, elapsed: float) -> str:
    """Render one scenario as a markdown transcript."""
    lines = [
        f"# Сценарий {scenario['id']}. {scenario['title']}",
        "",
        f"**Что проверяем:** {scenario['expect']}",
        "",
        "---",
        "",
        "### Запрос",
        "",
        f"> {scenario['question']}",
        "",
        "### Ответ агента",
        "",
        state.get("answer", "(пусто)"),
        "",
        "---",
        "",
        "### Что происходило внутри",
        "",
        f"- Ветка графа: `{state.get('route', '?')}`",
        f"- База отчётов использована: **{'да' if state.get('used_reports') else 'нет'}**",
        f"- Веб-поиск использован: **{'да' if state.get('used_web') else 'нет'}**",
        f"- Время ответа: {elapsed:.1f} с",
    ]

    report_hits = state.get("report_hits") or []
    if report_hits:
        lines += ["", "#### Фрагменты из отчётов", ""]
        for hit in report_hits:
            pages = f"с. {hit.page}" + (f"–{hit.page_end}" if hit.page_end != hit.page else "")
            lines.append(f"- `{hit.score:.3f}` — {hit.source_name}, {hit.date}, {pages}")

    web_hits = state.get("web_hits") or []
    if web_hits:
        lines += ["", "#### Веб-источники", ""]
        for hit in web_hits:
            mark = " ⭐ отраслевой" if hit.preferred else ""
            lines.append(f"- {hit.domain}{mark} — [{hit.title}]({hit.url})")

    if state.get("forecast_text"):
        lines += ["", "#### Выход расчётного модуля", "", "```", state["forecast_text"], "```"]

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="demo")
    parser.add_argument("--only", type=int, default=0, help="прогнать один сценарий по номеру")
    args = parser.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    scenarios = [s for s in SCENARIOS if not args.only or s["id"] == args.only]

    print(f"LLM: {settings.llm_model} @ {settings.llm_base_url}")
    print(f"Сценариев к прогону: {len(scenarios)}")
    print()

    summary = []
    for scenario in scenarios:
        print(f"--- {scenario['id']}. {scenario['title']}")
        started = time.monotonic()
        try:
            state = answer_question(scenario["question"])
        except Exception:  # noqa: BLE001
            print(traceback.format_exc(limit=3))
            summary.append((scenario["id"], "ОШИБКА", 0.0))
            continue
        elapsed = time.monotonic() - started

        path = out_dir / f"{scenario['id']:02d}-{scenario['title'].replace(' ', '-')}.md"
        path.write_text(render(scenario, state, elapsed), encoding="utf-8")

        sources = []
        if state.get("used_reports"):
            sources.append("отчёты")
        if state.get("used_web"):
            sources.append("веб")
        if state.get("forecast_text"):
            sources.append("расчёт")
        print(
            f"    {elapsed:5.1f} с | ветка {state.get('route', '?')} | "
            f"{' + '.join(sources) or 'без источников'} → {path.name}"
        )
        summary.append((scenario["id"], state.get("route", "?"), elapsed))

    print()
    print("Готово. Транскрипты:", out_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
